name: Ansible Playbook
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker run Linux
        env:
          DOCKER_REGISTRY_URL: https://index.docker.io/v1/
        run: sudo docker run -d -t --name=mycontainer centos:7

      - name: Install Ansible galaxy roles 
        run: ansible-galaxy install -r roles/requirements.yml

      - name: ansible
        run: ansible-playbook -i 'mycontainer,' -c docker -u root install.yml